version: '3.8'

services:
  # Main application
  reels-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reels-to-telegram
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - MAX_MEMORY_PER_VIDEO=${MAX_MEMORY_PER_VIDEO:-52428800}
      - MAX_TOTAL_MEMORY=${MAX_TOTAL_MEMORY:-209715200}
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-3}
      - MAX_QUEUE_SIZE=${MAX_QUEUE_SIZE:-50}
      - DEBUG_MEMORY=${DEBUG_MEMORY:-false}
    volumes:
      - ./logs:/app/logs
      - ./cookies.txt:/app/cookies.txt
    networks:
      - reels-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  reels-network:
    driver: bridge
